backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img"
public_folder: "/assets/img"

local_backend: true
publish_mode: editorial_workflow
collections:
  - label: "Mosaic"
    name: "mosaic"
    folder: "src/mosaic"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Order"
        name: "order"
        widget: "number"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
  - label: "Developing"
    name: "developing"
    folder: "src/developing"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Order"
        name: "order"
        widget: "number"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
  - label: "Designing"
    name: "designing"
    folder: "src/designing"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Order"
        name: "order"
        widget: "number"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Icon"
            name: "icon"
            widget: "string"
            required: false
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
  - label: "Guideline"
    name: "guidelines"
    folder: "src/guidelines"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Order"
        name: "order"
        widget: "number"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
  - label: "Component"
    name: "components"
    folder: "src/components"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Chips"
        name: "chips"
        widget: "select"
        multiple: true
        options: [
          "Proposed",
          "Approved",
          "In design",
          "HTML/CSS: In development",
          "Web Component: In development",
          "HTML/CSS: Available",
          "Web Component: Available"
        ]
      - label: "Storybook"
        name: "storybook"
        widget: "string"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Icon"
            name: "icon"
            widget: "string"
            required: false
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
      - label: "Code"
        name: "code"
        widget: object
        required: false
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
          - label: "Preview"
            name: "preview"
            widget: "object"
            fields:
              - label: "Variants"
                name: "variants"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Template"
                    name: "template"
                    widget: "code"
                    default_language: "html"
                    allow_language_selection: false
                  - label: "Modifiers"
                    name: "modifiers"
                    widget: "list"
                    fields:
                      - label: "Name"
                        name: "name"
                        widget: "string"
                      - label: "Selector"
                        name: "selector"
                        widget: "string"
                      - label: "Select multiple?"
                        name: "select_multiple"
                        widget: "boolean"
                        required: false
                      - label: "Type"
                        name: "type"
                        widget: "select"
                        options: ["class", "attribute"]
                      - label: "Attribute"
                        name: "attribute"
                        widget: "object"
                        required: false
                        fields:
                          - { label: "Name", name: "name", widget: "string", required: false }
                          - { label: "Value", name: "value", widget: "string", required: false }
                      - label: "Classes"
                        name: "classes"
                        widget: "list"
                        required: false
                        fields:
                          - { label: "Name", name: "name", widget: "string", required: false }
                          - { label: "Value", name: "value", widget: "string", required: false }
                          - { label: "Default", name: "default", widget: "boolean", required: false }
      - label: "Status"
        name: "status"
        widget: object
        required: false
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
          - label: "Design"
            name: "design"
            widget: "select"
            options: ["Yes", "No"]
          - label: "Documentation"
            name: "documentation"
            widget: "select"
            options: ["Yes", "No"]
          - label: "HTML/CSS"
            name: "html_css"
            widget: "select"
            options: ["In queue", "In development", "Available", "Not applicable"]
          - label: "Web Component"
            name: "web_component"
            widget: "select"
            options: ["In queue", "In development", "Available", "Not applicable"]
  - label: "Forms"
    name: "Forms"
    folder: "src/forms"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Chips"
        name: "chips"
        widget: "select"
        multiple: true
        options: [
          "Proposed",
          "Approved",
          "In design",
          "HTML/CSS: In development",
          "Web Component: In development",
          "HTML/CSS: Available",
          "Web Component: Available"
        ]
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
      - label: "Code"
        name: "code"
        widget: object
        required: false
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
          - label: "Preview"
            name: "preview"
            widget: "object"
            fields:
              - label: "Variants"
                name: "variants"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Template"
                    name: "template"
                    widget: "code"
                    default_language: "html"
                    allow_language_selection: false
                  - label: "Modifiers"
                    name: "modifiers"
                    widget: "list"
                    fields:
                      - label: "Name"
                        name: "name"
                        widget: "string"
                      - label: "Selector"
                        name: "selector"
                        widget: "string"
                      - label: "Select multiple?"
                        name: "select_multiple"
                        widget: "boolean"
                        required: false
                      - label: "Type"
                        name: "type"
                        widget: "select"
                        options: ["class", "attribute"]
                      - label: "Attribute"
                        name: "attribute"
                        widget: "object"
                        required: false
                        fields:
                          - { label: "Name", name: "name", widget: "string", required: false }
                          - { label: "Value", name: "value", widget: "string", required: false }
                      - label: "Classes"
                        name: "classes"
                        widget: "list"
                        required: false
                        fields:
                          - { label: "Name", name: "name", widget: "string", required: false }
                          - { label: "Value", name: "value", widget: "string", required: false }
                          - { label: "Default", name: "default", widget: "boolean", required: false }
      - label: "Status"
        name: "status"
        widget: object
        required: false
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
          - label: "Design"
            name: "design"
            widget: "select"
            options: ["Yes", "No"]
          - label: "Documentation"
            name: "documentation"
            widget: "select"
            options: ["Yes", "No"]
          - label: "HTML/CSS"
            name: "html_css"
            widget: "select"
            options: ["In queue", "In development", "Available", "Not applicable"]
          - label: "Web Component"
            name: "web_component"
            widget: "select"
            options: ["In queue", "In development", "Available", "Not applicable"]
  - label: "Pattern"
    name: "patterns"
    folder: "src/patterns"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
  - label: "In App Guidance"
    name: "in_app_guidance"
    folder: "src/in-app-guidance"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Order"
        name: "order"
        widget: "number"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
  - label: "Help"
    name: "help"
    folder: "src/help"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Order"
        name: "order"
        widget: "number"
      - label: "Table of contents"
        name: "toc"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tabs"
        name: "tabs"
        widget: "list"
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hook"
            name: "hook"
            widget: "string"
            required: false
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
  - label: "Team"
    name: "team"
    folder: "src/team"
    identifier_field: name
    create: true
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Job Title"
        name: "job_title"
        widget: "string"
      - label: "Profile picture"
        name: "profile_picture"
        widget: "object"
        required: false
        fields:
          - label: "Img"
            name: "img"
            widget: "image"
            required: false
          - label: "Background colour"
            name: "background_colour"
            widget: "select"
            multiple: false
            options: ["blue", "yellow", "red", "green", "orange", "pink", "teal", "purple"]
            required: false
      - label: "Bio"
        name: "bio"
        widget: "markdown"
        required: false
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/_data/home.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Strap line, name: strap_line, widget: markdown}
          - label: "Personas"
            name: "personas"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Overline, name: overline, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Description, name: description, widget: markdown}
              - label: "Button"
                name: "button"
                widget: object
                fields:
                - label: "Label"
                  name: "label"
                  widget: "string"
                - label: "URL"
                  name: "url"
                  widget: "string"
          - label: "Content cards"
            name: "content_cards"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Description, name: description, widget: markdown}
              - label: "Button"
                name: "button"
                widget: object
                fields:
                - label: "Label"
                  name: "label"
                  widget: "string"
                - label: "URL"
                  name: "url"
                  widget: "string"
      - label: "Colour"
        name: "colour"
        file: "src/_data/colour.json"
        fields:
          - {label: Greyscale colours, name: greyscale_colours, widget: markdown}
          - {label: Contextual colours, name: contextual_colours, widget: markdown}
          - {label: Primary, name: primary, widget: markdown}
          - {label: Success, name: success, widget: markdown}
          - {label: Danger, name: danger, widget: markdown}
          - {label: Warning, name: warning, widget: markdown}
          - {label: Info, name: info, widget: markdown}



